//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoveAndFight {
	using System;
	
	
	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	internal class Images {
		
		private static global::System.Resources.ResourceManager resourceMan;
		
		private static global::System.Globalization.CultureInfo resourceCulture;
		
		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal Images() {
		}
		
		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MoveAndFight.Images", typeof(Images).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}
		
		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}
		
		internal static System.Drawing.Bitmap arrow_leftturn_1 {
			get {
				object obj = ResourceManager.GetObject("arrow_leftturn_1", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap arrow_leftturn_2 {
			get {
				object obj = ResourceManager.GetObject("arrow_leftturn_2", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap arrow_leftturn_3 {
			get {
				object obj = ResourceManager.GetObject("arrow_leftturn_3", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap arrow_leftturn_4 {
			get {
				object obj = ResourceManager.GetObject("arrow_leftturn_4", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap arrow_north_1 {
			get {
				object obj = ResourceManager.GetObject("arrow_north_1", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap arrow_north_2 {
			get {
				object obj = ResourceManager.GetObject("arrow_north_2", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap arrow_north_3 {
			get {
				object obj = ResourceManager.GetObject("arrow_north_3", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap arrow_north_4 {
			get {
				object obj = ResourceManager.GetObject("arrow_north_4", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap arrow_rightturn_1 {
			get {
				object obj = ResourceManager.GetObject("arrow_rightturn_1", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap arrow_rightturn_2 {
			get {
				object obj = ResourceManager.GetObject("arrow_rightturn_2", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap arrow_rightturn_3 {
			get {
				object obj = ResourceManager.GetObject("arrow_rightturn_3", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap arrow_rightturn_4 {
			get {
				object obj = ResourceManager.GetObject("arrow_rightturn_4", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap baddie {
			get {
				object obj = ResourceManager.GetObject("baddie", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap closeCombat {
			get {
				object obj = ResourceManager.GetObject("closeCombat", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap dead_baddie {
			get {
				object obj = ResourceManager.GetObject("dead_baddie", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap hero_east_1 {
			get {
				object obj = ResourceManager.GetObject("hero_east_1", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap hero_east_2 {
			get {
				object obj = ResourceManager.GetObject("hero_east_2", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap hero_east_3 {
			get {
				object obj = ResourceManager.GetObject("hero_east_3", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap hero_east_4 {
			get {
				object obj = ResourceManager.GetObject("hero_east_4", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap hero_north_1 {
			get {
				object obj = ResourceManager.GetObject("hero_north_1", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap hero_north_2 {
			get {
				object obj = ResourceManager.GetObject("hero_north_2", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap hero_north_3 {
			get {
				object obj = ResourceManager.GetObject("hero_north_3", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap hero_north_4 {
			get {
				object obj = ResourceManager.GetObject("hero_north_4", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap hero_select_1 {
			get {
				object obj = ResourceManager.GetObject("hero_select_1", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap hero_select_2 {
			get {
				object obj = ResourceManager.GetObject("hero_select_2", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap hero_select_3 {
			get {
				object obj = ResourceManager.GetObject("hero_select_3", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap hero_select_4 {
			get {
				object obj = ResourceManager.GetObject("hero_select_4", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap hero_south_1 {
			get {
				object obj = ResourceManager.GetObject("hero_south_1", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap hero_south_2 {
			get {
				object obj = ResourceManager.GetObject("hero_south_2", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap hero_south_3 {
			get {
				object obj = ResourceManager.GetObject("hero_south_3", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap hero_south_4 {
			get {
				object obj = ResourceManager.GetObject("hero_south_4", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap hero_west_1 {
			get {
				object obj = ResourceManager.GetObject("hero_west_1", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap hero_west_2 {
			get {
				object obj = ResourceManager.GetObject("hero_west_2", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap hero_west_3 {
			get {
				object obj = ResourceManager.GetObject("hero_west_3", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap hero_west_4 {
			get {
				object obj = ResourceManager.GetObject("hero_west_4", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap rangedCombat {
			get {
				object obj = ResourceManager.GetObject("rangedCombat", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap room3x5 {
			get {
				object obj = ResourceManager.GetObject("room3x5", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap room4x4 {
			get {
				object obj = ResourceManager.GetObject("room4x4", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap room5x5 {
			get {
				object obj = ResourceManager.GetObject("room5x5", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
	}
}
